from arelle import XPathContext as XPathContext, XbrlConst as XbrlConst, XmlUtil as XmlUtil
from arelle.ModelFormulaObject import Aspect as Aspect, aspectModels as aspectModels, aspectStr as aspectStr
from arelle.ModelRenderingObject import CHILD_ROLLUP_FIRST as CHILD_ROLLUP_FIRST, CHILD_ROLLUP_LAST as CHILD_ROLLUP_LAST, ModelBreakdown as ModelBreakdown, ModelClosedDefinitionNode as ModelClosedDefinitionNode, ModelDefinitionNode as ModelDefinitionNode, ModelDimensionRelationshipDefinitionNode as ModelDimensionRelationshipDefinitionNode, ModelEuAxisCoord as ModelEuAxisCoord, ModelFilterDefinitionNode as ModelFilterDefinitionNode, ModelRuleDefinitionNode as ModelRuleDefinitionNode
from arelle.ModelValue import QName as QName

def init(modelXbrl) -> None: ...
def checkBreakdownDefinitionNode(modelXbrl, modelTable, tblAxisRel, tblAxisDisposition, uncoverableAspects, aspectsCovered): ...
def checkBreakdownLeafNodeAspects(modelXbrl, modelTable, tblAxisRel, parentAspectsCovered, breakdownAspects) -> None: ...
