from _typeshed import Incomplete
from datetime import datetime

def authority(url: str, includeScheme: bool = ...) -> str: ...
def scheme(url: str) -> Union[str, None]: ...

absoluteUrlPattern: Incomplete
relativeUrlPattern: Incomplete

def splitDecodeFragment(url: str) -> tuple[str, str]: ...
def anyUriQuoteForPSVI(uri: str) -> str: ...
def isValidAbsolute(url: str) -> bool: ...
def isValidUriReference(url: str) -> bool: ...
def isAbsolute(url: str) -> bool: ...
def isHttpUrl(url: str) -> bool: ...
def ensureUrl(maybeUrl: str) -> str: ...
def parseRfcDatetime(rfc2822date: str) -> Union[datetime, None]: ...

zipRelativeFilePattern: Incomplete

def relativeUri(baseUri: str, relativeUri: str) -> str: ...
