from _typeshed import Incomplete
from arelle.ModelValue import qname as qname

xsd: str
qnXsdSchema: Incomplete
qnXsdAppinfo: Incomplete
qnXsdDefaultType: Incomplete
xsi: str
qnXsiNil: Incomplete
qnXmlLang: Incomplete
builtinAttributes: Incomplete
xml: str
xbrli: str
eurofilingModelNamespace: str
eurofilingModelPrefix: str
qnNsmap: Incomplete
qnXbrliXbrl: Incomplete
qnPrototypeXbrliXbrl: Incomplete
qnXbrliItem: Incomplete
qnXbrliNumerator: Incomplete
qnXbrliDenominator: Incomplete
qnXbrliTuple: Incomplete
qnXbrliContext: Incomplete
qnXbrliPeriod: Incomplete
qnXbrliIdentifier: Incomplete
qnXbrliUnit: Incomplete
qnXbrliStringItemType: Incomplete
qnXbrliMonetaryItemType: Incomplete
qnXbrliDateItemType: Incomplete
qnXbrliDurationItemType: Incomplete
qnXbrliBooleanItemType: Incomplete
qnXbrliQNameItemType: Incomplete
qnXbrliPure: Incomplete
qnXbrliShares: Incomplete
qnInvalidMeasure: Incomplete
qnXbrliDateUnion: Incomplete
qnDateUnionXsdTypes: Incomplete
qnXbrliDecimalsUnion: Incomplete
qnXbrliPrecisionUnion: Incomplete
qnXbrliNonZeroDecimalUnion: Incomplete
link: str
qnLinkLinkbase: Incomplete
qnLinkLinkbaseRef: Incomplete
qnLinkLoc: Incomplete
qnLinkLabelLink: Incomplete
qnLinkLabelArc: Incomplete
qnLinkLabel: Incomplete
qnLinkReferenceLink: Incomplete
qnLinkReferenceArc: Incomplete
qnLinkReference: Incomplete
qnLinkPart: Incomplete
qnLinkFootnoteLink: Incomplete
qnLinkFootnoteArc: Incomplete
qnLinkFootnote: Incomplete
qnLinkPresentationLink: Incomplete
qnLinkPresentationArc: Incomplete
qnLinkCalculationLink: Incomplete
qnLinkCalculationArc: Incomplete
qnLinkDefinitionLink: Incomplete
qnLinkDefinitionArc: Incomplete
gen: str
qnGenLink: Incomplete
qnGenArc: Incomplete
elementReference: str
genReference: str
qnGenReference: Incomplete
elementLabel: str
genLabel: str
qnGenLabel: Incomplete
xbrldt: str
qnXbrldtHypercubeItem: Incomplete
qnXbrldtDimensionItem: Incomplete
qnXbrldtContextElement: Incomplete
xbrldi: str
qnXbrldiExplicitMember: Incomplete
qnXbrldiTypedMember: Incomplete
xlink: str
xl: str
qnXlExtended: Incomplete
qnXlLocator: Incomplete
qnXlResource: Incomplete
qnXlExtendedType: Incomplete
qnXlLocatorType: Incomplete
qnXlResourceType: Incomplete
qnXlArcType: Incomplete
xhtml: str
ixbrl: str
ixbrl11: str
ixbrlAll: Incomplete
ixbrlTags: Incomplete
ixbrlTagPattern: Incomplete
qnIXbrlResources: Incomplete
qnIXbrlTuple: Incomplete
qnIXbrlNonNumeric: Incomplete
qnIXbrlNonFraction: Incomplete
qnIXbrlFraction: Incomplete
qnIXbrlNumerator: Incomplete
qnIXbrlDenominator: Incomplete
qnIXbrlFootnote: Incomplete
qnIXbrl11Resources: Incomplete
qnIXbrl11Tuple: Incomplete
qnIXbrl11NonNumeric: Incomplete
qnIXbrl11NonFraction: Incomplete
qnIXbrl11Fraction: Incomplete
qnIXbrl11Numerator: Incomplete
qnIXbrl11Denominator: Incomplete
qnIXbrl11Footnote: Incomplete
qnIXbrl11Relationship: Incomplete
qnIXbrl11Hidden: Incomplete
ixAttributes: Incomplete
conceptLabel: str
conceptReference: str
footnote: str
factFootnote: str
factExplanatoryFact: str
parentChild: str
summationItem: str
essenceAlias: str
similarTuples: str
requiresElement: str
generalSpecial: str
dimStartsWith: str
all: str
notAll: str
hypercubeDimension: str
dimensionDomain: str
domainMember: str
dimensionDefault: str
defaultLinkRole: str
defaultGenLinkRole: str
iso4217: str
iso17442: str

def qnIsoCurrency(token): ...

standardLabel: str
genStandardLabel: str
documentationLabel: str
genDocumentationLabel: str
standardReference: str
genStandardReference: str
periodStartLabel: str
periodEndLabel: str
verboseLabel: str
terseLabel: str
conceptNameLabelRole: str
xlinkLinkbase: str
utr: str
dtr: str
dtrTypesStartsWith: str
dtrNumeric: str
dtrNoDecimalsItemTypes: Incomplete
dtrPrefixedContentItemTypes: Incomplete
dtrPrefixedContentTypes: Incomplete
dtrSQNameItemTypes: Incomplete
dtrSQNameTypes: Incomplete
dtrSQNamesItemTypes: Incomplete
dtrSQNamesTypes: Incomplete
dtrSQNameNamesItemTypes: Incomplete
dtrSQNameNamesTypes: Incomplete
wgnStringItemTypeNames: Incomplete
dtrNoLangItemTypeNames: Incomplete
xsdNoLangTypeNames: Incomplete
xsdStringTypeNames: Incomplete
ver10: str
vercb: str
verce: str
verrels: str
veria: str
ver: str
vercu: str
vercd: str
verdim: str
verPrefixNS: Incomplete
enum2s: Incomplete
enums: Incomplete
qnEnumerationItemType2014: Incomplete
qnEnumerationItemType2020: Incomplete
qnEnumerationItemTypeYYYY: Incomplete
qnEnumerationSetItemType2020: Incomplete
qnEnumerationSetItemTypeYYYY: Incomplete
qnEnumerationSetValDimType2020: Incomplete
qnEnumerationSetValDimTypeYYYY: Incomplete
qnEnumerationItemType11YYYY: Incomplete
qnEnumerationSetItemType11YYYY: Incomplete
qnEnumerationListItemType11YYYY: Incomplete
qnEnumerationItemType2016: Incomplete
qnEnumerationsItemType2016: Incomplete
qnEnumerationListItemTypes: Incomplete
qnEnumerationSetItemTypes: Incomplete
qnEnumeration2ItemTypes: Incomplete
qnEnumerationItemTypes: Incomplete
qnEnumerationTypes: Incomplete
attrEnumerationDomain2014: str
attrEnumerationDomain2020: str
attrEnumerationDomainYYYY: str
attrEnumerationDomain11YYYY: str
attrEnumerationDomain2016: str
attrEnumerationLinkrole2014: str
attrEnumerationLinkrole2020: str
attrEnumerationLinkroleYYYY: str
attrEnumerationLinkrole11YYYY: str
attrEnumerationLinkrole2016: str
attrEnumerationUsable2014: str
attrEnumerationUsable2020: str
attrEnumerationUsableYYYY: str
attrEnumerationUsable11YYYY: str
attrEnumerationUsable2016: str
variable: str
qnVariableSet: Incomplete
qnVariableVariable: Incomplete
qnVariableFilter: Incomplete
qnVariableFilterArc: Incomplete
qnParameter: Incomplete
qnFactVariable: Incomplete
qnGeneralVariable: Incomplete
qnPrecondition: Incomplete
qnEqualityDefinition: Incomplete
qnEqualityTestA: Incomplete
qnEqualityTestB: Incomplete
formula: str
tuple: str
qnFormula: Incomplete
qnTuple: Incomplete
qnFormulaUncovered: Incomplete
qnFormulaDimensionSAV: Incomplete
qnFormulaOccEmpty: Incomplete
ca: str
qnConsistencyAssertion: Incomplete
qnCaAspectMatchedFacts: Incomplete
qnCaAcceptanceRadius: Incomplete
qnCaAbsoluteAcceptanceRadiusExpression: Incomplete
qnCaProportionalAcceptanceRadiusExpression: Incomplete
ea: str
qnExistenceAssertion: Incomplete
qnEaTestExpression: Incomplete
va: str
qnValueAssertion: Incomplete
qnVaTestExpression: Incomplete
formulaStartsWith: str
equalityDefinition: str
variableSet: str
variableSetFilter: str
variableFilter: str
variableSetPrecondition: str
consistencyAssertionFormula: str
consistencyAssertionParameter: str
validation: str
qnAssertion: Incomplete
qnVariableSetAssertion: Incomplete
qnAssertionSet: Incomplete
assertionSet: str
assertionUnsatisfiedSeverity: str
assertionUnsatisfiedSeverity20: str
assertionUnsatisfiedSeverities: Incomplete
qnAssertionSeverityError: Incomplete
qnAssertionSeverityWarning: Incomplete
qnAssertionSeverityOk: Incomplete
qnAssertionSeverityError20: Incomplete
qnAssertionSeverityWarning20: Incomplete
qnAssertionSeverityOk20: Incomplete
qnAssertionSeverityExpression20: Incomplete
acf: str
qnAspectCover: Incomplete
bf: str
qnAndFilter: Incomplete
qnOrFilter: Incomplete
booleanFilter: str
cfi: str
functionImplementation: str
qnCustomFunctionSignature: Incomplete
qnCustomFunctionImplementation: Incomplete
crf: str
qnConceptRelation: Incomplete
cf: str
qnConceptName: Incomplete
qnConceptPeriodType: Incomplete
qnConceptBalance: Incomplete
qnConceptCustomAttribute: Incomplete
qnConceptDataType: Incomplete
qnConceptSubstitutionGroup: Incomplete
cfcn: str
df: str
qnExplicitDimension: Incomplete
qnTypedDimension: Incomplete
ef: str
qnEntityIdentifier: Incomplete
qnEntitySpecificIdentifier: Incomplete
qnEntitySpecificScheme: Incomplete
qnEntityRegexpIdentifier: Incomplete
qnEntityRegexpScheme: Incomplete
function: str
fn: str
xfi: str
qnXfiRoot: Incomplete
xff: str
gf: str
qnGeneral: Incomplete
instances: str
qnInstance: Incomplete
instanceVariable: str
formulaInstance: str
qnStandardInputInstance: Incomplete
qnStandardOutputInstance: Incomplete
mf: str
qnMatchConcept: Incomplete
qnMatchDimension: Incomplete
qnMatchEntityIdentifier: Incomplete
qnMatchLocation: Incomplete
qnMatchPeriod: Incomplete
qnMatchSegment: Incomplete
qnMatchScenario: Incomplete
qnMatchNonXDTSegment: Incomplete
qnMatchNonXDTScenario: Incomplete
qnMatchUnit: Incomplete
msg: str
qnMessage: Incomplete
assertionSatisfiedMessage: str
assertionUnsatisfiedMessage: str
standardMessage: str
terseMessage: str
verboseMessage: str
pf: str
qnPeriod: Incomplete
qnPeriodStart: Incomplete
qnPeriodEnd: Incomplete
qnPeriodInstant: Incomplete
qnForever: Incomplete
qnInstantDuration: Incomplete
registry: str
rf: str
qnRelativeFilter: Incomplete
ssf: str
qnSegmentFilter: Incomplete
qnScenarioFilter: Incomplete
tf: str
qnAncestorFilter: Incomplete
qnLocationFilter: Incomplete
qnParentFilter: Incomplete
qnSiblingFilter: Incomplete
uf: str
qnSingleMeasure: Incomplete
qnGeneralMeasures: Incomplete
vf: str
qnNilFilter: Incomplete
qnPrecisionFilter: Incomplete
xpath2err: str
variablesScope: str
tableMMDD: str
tableModelMMDD: str
tableBreakdownMMDD: str
tableBreakdownTreeMMDD: str
tableDefinitionNodeSubtreeMMDD: str
tableFilterMMDD: str
tableAspectNodeFilterMMDD: str
tableParameterMMDD: str
qnTableTableMMDD: Incomplete
qnTableBreakdownMMDD: Incomplete
qnTableRuleNodeMMDD: Incomplete
qnTableRuleSetMMDD: Incomplete
qnTableDefinitionNodeMMDD: Incomplete
qnTableClosedDefinitionNodeMMDD: Incomplete
qnTableConceptRelationshipNodeMMDD: Incomplete
qnTableDimensionRelationshipNodeMMDD: Incomplete
qnTableAspectNodeMMDD: Incomplete
table: str
tableModel: str
tableBreakdown: str
tableBreakdownTree: str
tableDefinitionNodeSubtree: str
tableFilter: str
tableAspectNodeFilter: str
tableParameter: str
qnTableTable: Incomplete
qnTableBreakdown: Incomplete
qnTableRuleNode: Incomplete
qnTableRuleSet: Incomplete
qnTableDefinitionNode: Incomplete
qnTableClosedDefinitionNode: Incomplete
qnTableConceptRelationshipNode: Incomplete
qnTableDimensionRelationshipNode: Incomplete
qnTableAspectNode: Incomplete
table201305: str
tableModel201305: str
tableBreakdown201305: str
tableBreakdownTree201305: str
tableDefinitionNodeSubtree201305: str
tableFilter201305: str
tableAspectNodeFilter201305: str
qnTableTable201305: Incomplete
qnTableBreakdown201305: Incomplete
qnTableRuleNode201305: Incomplete
qnTableClosedDefinitionNode201305: Incomplete
qnTableConceptRelationshipNode201305: Incomplete
qnTableDimensionRelationshipNode201305: Incomplete
qnTableAspectNode201305: Incomplete
table201301: str
tableBreakdown201301: str
tableFilter201301: str
tableDefinitionNodeSubtree201301: str
tableTupleContent201301: str
tableDefinitionNodeMessage201301: str
tableDefinitionNodeSelectionMessage201301: str
qnTableTable201301: Incomplete
qnTableCompositionNode201301: Incomplete
qnTableFilterNode201301: Incomplete
qnTableConceptRelationshipNode201301: Incomplete
qnTableDimensionRelationshipNode201301: Incomplete
qnTableRuleNode201301: Incomplete
qnTableClosedDefinitionNode201301: Incomplete
qnTableSelectionNode201301: Incomplete
qnTableTupleNode201301: Incomplete
table2011: str
tableAxis2011: str
tableAxisSubtree2011: str
tableFilter2011: str
tableFilterNodeFilter2011: str
tableAxisFilter2011: str
tableAxisFilter201205: str
tableTupleContent2011: str
tableAxisMessage2011: str
tableAxisSelectionMessage2011: str
qnTableTable2011: Incomplete
qnTableCompositionAxis2011: Incomplete
qnTableFilterAxis2011: Incomplete
qnTableConceptRelationshipAxis2011: Incomplete
qnTableDimensionRelationshipAxis2011: Incomplete
qnTableRuleAxis2011: Incomplete
qnTablePredefinedAxis2011: Incomplete
qnTableSelectionAxis2011: Incomplete
qnTableTupleAxis2011: Incomplete
booleanValueTrue: str
booleanValueFalse: str
euRend: str
euTableAxis: str
euAxisMember: str
qnEuTable: Incomplete
qnEuAxisCoord: Incomplete
euGroupTable: str
widerNarrower: str
xdtSchemaErrorNS: str
errMsgPrefixNS: Incomplete
qnEuFiTuple: Incomplete
qnEuFiIndFact: Incomplete
cnEuFiIndAttr: str
qnFiFact: Incomplete
qnFiDim: Incomplete
arcroleGroupDetect: str

def baseSetArcroleLabel(arcrole): ...
def labelroleLabel(role): ...
def isStandardNamespace(namespaceURI) -> bool: ...

standardNamespaceSchemaLocations: Incomplete

def isNumericXsdType(xsdType): ...
def isIntegerXsdType(xsdType): ...

standardLabelRoles: Incomplete
standardReferenceRoles: Incomplete
standardLinkbaseRefRoles: Incomplete
standardRoles: Incomplete

def isStandardRole(role): ...
def isTotalRole(role): ...
def isNetRole(role): ...
def isLabelRole(role): ...
def isNumericRole(role): ...
def isStandardArcrole(role): ...

standardArcroleCyclesAllowed: Incomplete

def standardArcroleArcElement(arcrole): ...
def isDefinitionOrXdtArcrole(arcrole): ...
def isStandardResourceOrExtLinkElement(element): ...
def isStandardArcElement(element): ...
def isStandardArcInExtLinkElement(element): ...

standardExtLinkQnames: Incomplete
standardExtLinkQnamesAndResources: Incomplete

def isStandardExtLinkQname(qName) -> bool: ...
def isStandardArcQname(qName) -> bool: ...
def isDimensionArcrole(arcrole): ...

consecutiveArcrole: Incomplete

def isTableRenderingArcrole(arcrole): ...

tableIndexingArcroles: Incomplete

def isTableIndexingArcrole(arcrole): ...
def isFormulaArcrole(arcrole): ...
def isResourceArcrole(arcrole): ...

lrrRoleHrefs: Incomplete
lrrArcroleHrefs: Incomplete
lrrUnapprovedRoles: Incomplete
lrrUnapprovedArcroles: Incomplete
