name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9']

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: xbrlreportsindexes

    - name: Checkout Arelle master
      uses: actions/checkout@v3
      with:
        repository: Arelle/Arelle
        path: Arelle

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox==3.26.0 tox-gh-actions
    - name: Test with tox
      run:  |
            if [ "$RUNNER_OS" == "Linux" ]; then
                  cd xbrlreportsindexes
                  PYTHONPATH=$GITHUB_WORKSPACE/Arelle tox
            elif [ "$RUNNER_OS" == "Windows" ]; then
                  echo $GITHUB_WORKSPACE
                  export PYTHONPATH=$GITHUB_WORKSPACE/Arelle
                  echo $PYTHONPATH
                  cd xbrlreportsindexes
                  tox
            else
                  echo "$RUNNER_OS not supported"
                  exit 1
            fi
      shell: bash